//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KURSAVAYA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Банк данные.
    /// </summary>
    // *** Start programmer edit section *** (БанкДанные CustomAttributes)

    // *** End programmer edit section *** (БанкДанные CustomAttributes)
    [AutoAltered()]
    [Caption("Банк данные")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БанкДанныеE", new string[] {
            "НомерКарт as \'Номер карт\'",
            "CVV as \'CVV\'",
            "ДатаОконч as \'Дата оконч\'"})]
    [View("БанкДанныеL", new string[] {
            "НомерКарт as \'Номер карт\'",
            "CVV as \'CVV\'",
            "ДатаОконч as \'Дата оконч\'"})]
    public class БанкДанные : ICSSoft.STORMNET.DataObject
    {
        
        private long fНомерКарт;
        
        private int fCVV;
        
        private System.DateTime fДатаОконч;
        
        // *** Start programmer edit section *** (БанкДанные CustomMembers)

        // *** End programmer edit section *** (БанкДанные CustomMembers)

        
        /// <summary>
        /// CVV.
        /// </summary>
        // *** Start programmer edit section *** (БанкДанные.CVV CustomAttributes)

        // *** End programmer edit section *** (БанкДанные.CVV CustomAttributes)
        [NotNull()]
        public virtual int CVV
        {
            get
            {
                // *** Start programmer edit section *** (БанкДанные.CVV Get start)

                // *** End programmer edit section *** (БанкДанные.CVV Get start)
                int result = this.fCVV;
                // *** Start programmer edit section *** (БанкДанные.CVV Get end)

                // *** End programmer edit section *** (БанкДанные.CVV Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БанкДанные.CVV Set start)

                // *** End programmer edit section *** (БанкДанные.CVV Set start)
                this.fCVV = value;
                // *** Start programmer edit section *** (БанкДанные.CVV Set end)

                // *** End programmer edit section *** (БанкДанные.CVV Set end)
            }
        }
        
        /// <summary>
        /// ДатаОконч.
        /// </summary>
        // *** Start programmer edit section *** (БанкДанные.ДатаОконч CustomAttributes)

        // *** End programmer edit section *** (БанкДанные.ДатаОконч CustomAttributes)
        [NotNull()]
        public virtual System.DateTime ДатаОконч
        {
            get
            {
                // *** Start programmer edit section *** (БанкДанные.ДатаОконч Get start)

                // *** End programmer edit section *** (БанкДанные.ДатаОконч Get start)
                System.DateTime result = this.fДатаОконч;
                // *** Start programmer edit section *** (БанкДанные.ДатаОконч Get end)

                // *** End programmer edit section *** (БанкДанные.ДатаОконч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БанкДанные.ДатаОконч Set start)

                // *** End programmer edit section *** (БанкДанные.ДатаОконч Set start)
                this.fДатаОконч = value;
                // *** Start programmer edit section *** (БанкДанные.ДатаОконч Set end)

                // *** End programmer edit section *** (БанкДанные.ДатаОконч Set end)
            }
        }
        
        /// <summary>
        /// НомерКарт.
        /// </summary>
        // *** Start programmer edit section *** (БанкДанные.НомерКарт CustomAttributes)

        // *** End programmer edit section *** (БанкДанные.НомерКарт CustomAttributes)
        [NotNull()]
        public virtual long НомерКарт
        {
            get
            {
                // *** Start programmer edit section *** (БанкДанные.НомерКарт Get start)

                // *** End programmer edit section *** (БанкДанные.НомерКарт Get start)
                long result = this.fНомерКарт;
                // *** Start programmer edit section *** (БанкДанные.НомерКарт Get end)

                // *** End programmer edit section *** (БанкДанные.НомерКарт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БанкДанные.НомерКарт Set start)

                // *** End programmer edit section *** (БанкДанные.НомерКарт Set start)
                this.fНомерКарт = value;
                // *** Start programmer edit section *** (БанкДанные.НомерКарт Set end)

                // *** End programmer edit section *** (БанкДанные.НомерКарт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БанкДанныеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БанкДанныеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БанкДанныеE", typeof(IIS.KURSAVAYA.БанкДанные));
                }
            }
            
            /// <summary>
            /// "БанкДанныеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БанкДанныеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БанкДанныеL", typeof(IIS.KURSAVAYA.БанкДанные));
                }
            }
        }
    }
}
