//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KURSAVAYA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заправка авто.
    /// </summary>
    // *** Start programmer edit section *** (ЗаправкаАвто CustomAttributes)

    // *** End programmer edit section *** (ЗаправкаАвто CustomAttributes)
    [AutoAltered()]
    [Caption("Заправка авто")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаправкаАвтоE", new string[] {
            "КолТоплива as \'Кол топлива\'",
            "Колонка as \'Колонка\'",
            "Колонка.НомерКол as \'Номер кол\'"}, Hidden=new string[] {
            "Колонка.НомерКол"})]
    [MasterViewDefineAttribute("ЗаправкаАвтоE", "Колонка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКол")]
    [View("ЗаправкаАвтоL", new string[] {
            "КолТоплива as \'Кол топлива\'",
            "Колонка.НомерКол as \'Номер кол\'"})]
    public class ЗаправкаАвто : ICSSoft.STORMNET.DataObject
    {
        
        private int fКолТоплива;
        
        private IIS.KURSAVAYA.Колонка fКолонка;
        
        // *** Start programmer edit section *** (ЗаправкаАвто CustomMembers)

        // *** End programmer edit section *** (ЗаправкаАвто CustomMembers)

        
        /// <summary>
        /// КолТоплива.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправкаАвто.КолТоплива CustomAttributes)

        // *** End programmer edit section *** (ЗаправкаАвто.КолТоплива CustomAttributes)
        [NotNull()]
        public virtual int КолТоплива
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправкаАвто.КолТоплива Get start)

                // *** End programmer edit section *** (ЗаправкаАвто.КолТоплива Get start)
                int result = this.fКолТоплива;
                // *** Start programmer edit section *** (ЗаправкаАвто.КолТоплива Get end)

                // *** End programmer edit section *** (ЗаправкаАвто.КолТоплива Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправкаАвто.КолТоплива Set start)

                // *** End programmer edit section *** (ЗаправкаАвто.КолТоплива Set start)
                this.fКолТоплива = value;
                // *** Start programmer edit section *** (ЗаправкаАвто.КолТоплива Set end)

                // *** End programmer edit section *** (ЗаправкаАвто.КолТоплива Set end)
            }
        }
        
        /// <summary>
        /// Заправка авто.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправкаАвто.Колонка CustomAttributes)

        // *** End programmer edit section *** (ЗаправкаАвто.Колонка CustomAttributes)
        [PropertyStorage(new string[] {
                "Колонка"})]
        [NotNull()]
        public virtual IIS.KURSAVAYA.Колонка Колонка
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправкаАвто.Колонка Get start)

                // *** End programmer edit section *** (ЗаправкаАвто.Колонка Get start)
                IIS.KURSAVAYA.Колонка result = this.fКолонка;
                // *** Start programmer edit section *** (ЗаправкаАвто.Колонка Get end)

                // *** End programmer edit section *** (ЗаправкаАвто.Колонка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправкаАвто.Колонка Set start)

                // *** End programmer edit section *** (ЗаправкаАвто.Колонка Set start)
                this.fКолонка = value;
                // *** Start programmer edit section *** (ЗаправкаАвто.Колонка Set end)

                // *** End programmer edit section *** (ЗаправкаАвто.Колонка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаправкаАвтоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаправкаАвтоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаправкаАвтоE", typeof(IIS.KURSAVAYA.ЗаправкаАвто));
                }
            }
            
            /// <summary>
            /// "ЗаправкаАвтоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаправкаАвтоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаправкаАвтоL", typeof(IIS.KURSAVAYA.ЗаправкаАвто));
                }
            }
        }
    }
}
