//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KURSAVAYA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заправ бак.
    /// </summary>
    // *** Start programmer edit section *** (ЗаправБак CustomAttributes)

    // *** End programmer edit section *** (ЗаправБак CustomAttributes)
    [AutoAltered()]
    [Caption("Заправ бак")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаправБакE", new string[] {
            "Объем as \'Объем\'",
            "ТипТоплива as \'Тип топлива\'",
            "УровеньЗаливки as \'Уровень заливки\'",
            "Активен as \'Активен\'",
            "ЦенаТопл as \'Цена топл\'"})]
    [View("ЗаправБакL", new string[] {
            "Объем as \'Объем\'",
            "ТипТоплива as \'Тип топлива\'",
            "УровеньЗаливки as \'Уровень заливки\'",
            "Активен as \'Активен\'",
            "ЦенаТопл as \'Цена топл\'"})]
    public class ЗаправБак : ICSSoft.STORMNET.DataObject
    {
        
        private int fОбъем;
        
        private string fТипТоплива;
        
        private int fУровеньЗаливки;
        
        private bool fАктивен;
        
        private float fЦенаТопл;
        
        // *** Start programmer edit section *** (ЗаправБак CustomMembers)

        // *** End programmer edit section *** (ЗаправБак CustomMembers)

        
        /// <summary>
        /// Активен.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.Активен CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.Активен CustomAttributes)
        [NotNull()]
        public virtual bool Активен
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.Активен Get start)

                // *** End programmer edit section *** (ЗаправБак.Активен Get start)
                bool result = this.fАктивен;
                // *** Start programmer edit section *** (ЗаправБак.Активен Get end)

                // *** End programmer edit section *** (ЗаправБак.Активен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.Активен Set start)

                // *** End programmer edit section *** (ЗаправБак.Активен Set start)
                this.fАктивен = value;
                // *** Start programmer edit section *** (ЗаправБак.Активен Set end)

                // *** End programmer edit section *** (ЗаправБак.Активен Set end)
            }
        }
        
        /// <summary>
        /// Объем.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.Объем CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.Объем CustomAttributes)
        [NotNull()]
        public virtual int Объем
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.Объем Get start)

                // *** End programmer edit section *** (ЗаправБак.Объем Get start)
                int result = this.fОбъем;
                // *** Start programmer edit section *** (ЗаправБак.Объем Get end)

                // *** End programmer edit section *** (ЗаправБак.Объем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.Объем Set start)

                // *** End programmer edit section *** (ЗаправБак.Объем Set start)
                this.fОбъем = value;
                // *** Start programmer edit section *** (ЗаправБак.Объем Set end)

                // *** End programmer edit section *** (ЗаправБак.Объем Set end)
            }
        }
        
        /// <summary>
        /// ТипТоплива.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.ТипТоплива CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.ТипТоплива CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ТипТоплива
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.ТипТоплива Get start)

                // *** End programmer edit section *** (ЗаправБак.ТипТоплива Get start)
                string result = this.fТипТоплива;
                // *** Start programmer edit section *** (ЗаправБак.ТипТоплива Get end)

                // *** End programmer edit section *** (ЗаправБак.ТипТоплива Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.ТипТоплива Set start)

                // *** End programmer edit section *** (ЗаправБак.ТипТоплива Set start)
                this.fТипТоплива = value;
                // *** Start programmer edit section *** (ЗаправБак.ТипТоплива Set end)

                // *** End programmer edit section *** (ЗаправБак.ТипТоплива Set end)
            }
        }
        
        /// <summary>
        /// УровеньЗаливки.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.УровеньЗаливки CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.УровеньЗаливки CustomAttributes)
        [NotNull()]
        public virtual int УровеньЗаливки
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.УровеньЗаливки Get start)

                // *** End programmer edit section *** (ЗаправБак.УровеньЗаливки Get start)
                int result = this.fУровеньЗаливки;
                // *** Start programmer edit section *** (ЗаправБак.УровеньЗаливки Get end)

                // *** End programmer edit section *** (ЗаправБак.УровеньЗаливки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.УровеньЗаливки Set start)

                // *** End programmer edit section *** (ЗаправБак.УровеньЗаливки Set start)
                this.fУровеньЗаливки = value;
                // *** Start programmer edit section *** (ЗаправБак.УровеньЗаливки Set end)

                // *** End programmer edit section *** (ЗаправБак.УровеньЗаливки Set end)
            }
        }
        
        /// <summary>
        /// ЦенаТопл.
        /// </summary>
        // *** Start programmer edit section *** (ЗаправБак.ЦенаТопл CustomAttributes)

        // *** End programmer edit section *** (ЗаправБак.ЦенаТопл CustomAttributes)
        [NotNull()]
        public virtual float ЦенаТопл
        {
            get
            {
                // *** Start programmer edit section *** (ЗаправБак.ЦенаТопл Get start)

                // *** End programmer edit section *** (ЗаправБак.ЦенаТопл Get start)
                float result = this.fЦенаТопл;
                // *** Start programmer edit section *** (ЗаправБак.ЦенаТопл Get end)

                // *** End programmer edit section *** (ЗаправБак.ЦенаТопл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаправБак.ЦенаТопл Set start)

                // *** End programmer edit section *** (ЗаправБак.ЦенаТопл Set start)
                this.fЦенаТопл = value;
                // *** Start programmer edit section *** (ЗаправБак.ЦенаТопл Set end)

                // *** End programmer edit section *** (ЗаправБак.ЦенаТопл Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаправБакE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаправБакE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаправБакE", typeof(IIS.KURSAVAYA.ЗаправБак));
                }
            }
            
            /// <summary>
            /// "ЗаправБакL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаправБакL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаправБакL", typeof(IIS.KURSAVAYA.ЗаправБак));
                }
            }
        }
    }
}
