//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KURSAVAYA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "ЗаправкаАвто as \'Заправка авто\'",
            "ЗаправкаАвто.КолТоплива as \'Кол топлива\'",
            "Товар as \'Товар\'",
            "Товар.Наименование as \'Наименование\'",
            "Клиент as \'Клиент\'",
            "Клиент.Имя as \'Имя\'"}, Hidden=new string[] {
            "ЗаправкаАвто.КолТоплива",
            "Товар.Наименование",
            "Клиент.Имя"})]
    [MasterViewDefineAttribute("ЗаказE", "ЗаправкаАвто", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КолТоплива")]
    [MasterViewDefineAttribute("ЗаказE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ЗаказE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("ЗаказL", new string[] {
            "НомерЗаказа as \'Номер заказа\'",
            "ЗаправкаАвто.КолТоплива as \'Кол топлива\'",
            "Товар.Наименование as \'Наименование\'",
            "Клиент.Имя as \'Имя\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЗаказа;
        
        private IIS.KURSAVAYA.ЗаправкаАвто fЗаправкаАвто;
        
        private IIS.KURSAVAYA.Товар fТовар;
        
        private IIS.KURSAVAYA.Клиент fКлиент;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// НомерЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.НомерЗаказа CustomAttributes)
        [NotNull()]
        public virtual int НомерЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get start)
                int result = this.fНомерЗаказа;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Get end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set start)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set start)
                this.fНомерЗаказа = value;
                // *** Start programmer edit section *** (Заказ.НомерЗаказа Set end)

                // *** End programmer edit section *** (Заказ.НомерЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ЗаправкаАвто CustomAttributes)

        // *** End programmer edit section *** (Заказ.ЗаправкаАвто CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаправкаАвто"})]
        [NotNull()]
        public virtual IIS.KURSAVAYA.ЗаправкаАвто ЗаправкаАвто
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ЗаправкаАвто Get start)

                // *** End programmer edit section *** (Заказ.ЗаправкаАвто Get start)
                IIS.KURSAVAYA.ЗаправкаАвто result = this.fЗаправкаАвто;
                // *** Start programmer edit section *** (Заказ.ЗаправкаАвто Get end)

                // *** End programmer edit section *** (Заказ.ЗаправкаАвто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ЗаправкаАвто Set start)

                // *** End programmer edit section *** (Заказ.ЗаправкаАвто Set start)
                this.fЗаправкаАвто = value;
                // *** Start programmer edit section *** (Заказ.ЗаправкаАвто Set end)

                // *** End programmer edit section *** (Заказ.ЗаправкаАвто Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Клиент CustomAttributes)

        // *** End programmer edit section *** (Заказ.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.KURSAVAYA.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Клиент Get start)

                // *** End programmer edit section *** (Заказ.Клиент Get start)
                IIS.KURSAVAYA.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Заказ.Клиент Get end)

                // *** End programmer edit section *** (Заказ.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Клиент Set start)

                // *** End programmer edit section *** (Заказ.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Заказ.Клиент Set end)

                // *** End programmer edit section *** (Заказ.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Товар CustomAttributes)

        // *** End programmer edit section *** (Заказ.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.KURSAVAYA.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Товар Get start)

                // *** End programmer edit section *** (Заказ.Товар Get start)
                IIS.KURSAVAYA.Товар result = this.fТовар;
                // *** Start programmer edit section *** (Заказ.Товар Get end)

                // *** End programmer edit section *** (Заказ.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Товар Set start)

                // *** End programmer edit section *** (Заказ.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Заказ.Товар Set end)

                // *** End programmer edit section *** (Заказ.Товар Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.KURSAVAYA.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.KURSAVAYA.Заказ));
                }
            }
        }
    }
}
