//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KURSAVAYA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "Имя as \'Имя\'",
            "ТелНомер as \'Тел номер\'",
            "Фамилия as \'Фамилия\'",
            "ДатаРожд as \'Дата рожд\'",
            "БанкДанные as \'Банк данные\'",
            "БанкДанные.НомерКарт as \'Номер карт\'"}, Hidden=new string[] {
            "БанкДанные.НомерКарт"})]
    [MasterViewDefineAttribute("КлиентE", "БанкДанные", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКарт")]
    [View("КлиентL", new string[] {
            "Имя as \'Имя\'",
            "ТелНомер as \'Тел номер\'",
            "Фамилия as \'Фамилия\'",
            "ДатаРожд as \'Дата рожд\'",
            "БанкДанные.НомерКарт as \'Номер карт\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмя;
        
        private long fТелНомер;
        
        private string fФамилия;
        
        private System.DateTime fДатаРожд;
        
        private IIS.KURSAVAYA.БанкДанные fБанкДанные;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// ДатаРожд.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ДатаРожд CustomAttributes)

        // *** End programmer edit section *** (Клиент.ДатаРожд CustomAttributes)
        public virtual System.DateTime ДатаРожд
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ДатаРожд Get start)

                // *** End programmer edit section *** (Клиент.ДатаРожд Get start)
                System.DateTime result = this.fДатаРожд;
                // *** Start programmer edit section *** (Клиент.ДатаРожд Get end)

                // *** End programmer edit section *** (Клиент.ДатаРожд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ДатаРожд Set start)

                // *** End programmer edit section *** (Клиент.ДатаРожд Set start)
                this.fДатаРожд = value;
                // *** Start programmer edit section *** (Клиент.ДатаРожд Set end)

                // *** End programmer edit section *** (Клиент.ДатаРожд Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Имя CustomAttributes)

        // *** End programmer edit section *** (Клиент.Имя CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Имя Get start)

                // *** End programmer edit section *** (Клиент.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Клиент.Имя Get end)

                // *** End programmer edit section *** (Клиент.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Имя Set start)

                // *** End programmer edit section *** (Клиент.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Клиент.Имя Set end)

                // *** End programmer edit section *** (Клиент.Имя Set end)
            }
        }
        
        /// <summary>
        /// ТелНомер.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ТелНомер CustomAttributes)

        // *** End programmer edit section *** (Клиент.ТелНомер CustomAttributes)
        public virtual long ТелНомер
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ТелНомер Get start)

                // *** End programmer edit section *** (Клиент.ТелНомер Get start)
                long result = this.fТелНомер;
                // *** Start programmer edit section *** (Клиент.ТелНомер Get end)

                // *** End programmer edit section *** (Клиент.ТелНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ТелНомер Set start)

                // *** End programmer edit section *** (Клиент.ТелНомер Set start)
                this.fТелНомер = value;
                // *** Start programmer edit section *** (Клиент.ТелНомер Set end)

                // *** End programmer edit section *** (Клиент.ТелНомер Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Клиент.Фамилия CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Фамилия Get start)

                // *** End programmer edit section *** (Клиент.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Клиент.Фамилия Get end)

                // *** End programmer edit section *** (Клиент.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Фамилия Set start)

                // *** End programmer edit section *** (Клиент.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Клиент.Фамилия Set end)

                // *** End programmer edit section *** (Клиент.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Клиент.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.БанкДанные CustomAttributes)

        // *** End programmer edit section *** (Клиент.БанкДанные CustomAttributes)
        [PropertyStorage(new string[] {
                "БанкДанные"})]
        [NotNull()]
        public virtual IIS.KURSAVAYA.БанкДанные БанкДанные
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.БанкДанные Get start)

                // *** End programmer edit section *** (Клиент.БанкДанные Get start)
                IIS.KURSAVAYA.БанкДанные result = this.fБанкДанные;
                // *** Start programmer edit section *** (Клиент.БанкДанные Get end)

                // *** End programmer edit section *** (Клиент.БанкДанные Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.БанкДанные Set start)

                // *** End programmer edit section *** (Клиент.БанкДанные Set start)
                this.fБанкДанные = value;
                // *** Start programmer edit section *** (Клиент.БанкДанные Set end)

                // *** End programmer edit section *** (Клиент.БанкДанные Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.KURSAVAYA.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.KURSAVAYA.Клиент));
                }
            }
        }
    }
}
