//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KURSAVAYA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Колонка.
    /// </summary>
    // *** Start programmer edit section *** (Колонка CustomAttributes)

    // *** End programmer edit section *** (Колонка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КолонкаE", new string[] {
            "НомерКол as \'Номер кол\'",
            "ЗаправБак as \'Заправ бак\'",
            "ЗаправБак.ТипТоплива as \'Тип топлива\'"}, Hidden=new string[] {
            "ЗаправБак.ТипТоплива"})]
    [MasterViewDefineAttribute("КолонкаE", "ЗаправБак", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипТоплива")]
    [View("КолонкаL", new string[] {
            "НомерКол as \'Номер кол\'",
            "ЗаправБак.ТипТоплива as \'Тип топлива\'"})]
    public class Колонка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКол;
        
        private IIS.KURSAVAYA.ЗаправБак fЗаправБак;
        
        // *** Start programmer edit section *** (Колонка CustomMembers)

        // *** End programmer edit section *** (Колонка CustomMembers)

        
        /// <summary>
        /// НомерКол.
        /// </summary>
        // *** Start programmer edit section *** (Колонка.НомерКол CustomAttributes)

        // *** End programmer edit section *** (Колонка.НомерКол CustomAttributes)
        [NotNull()]
        public virtual int НомерКол
        {
            get
            {
                // *** Start programmer edit section *** (Колонка.НомерКол Get start)

                // *** End programmer edit section *** (Колонка.НомерКол Get start)
                int result = this.fНомерКол;
                // *** Start programmer edit section *** (Колонка.НомерКол Get end)

                // *** End programmer edit section *** (Колонка.НомерКол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Колонка.НомерКол Set start)

                // *** End programmer edit section *** (Колонка.НомерКол Set start)
                this.fНомерКол = value;
                // *** Start programmer edit section *** (Колонка.НомерКол Set end)

                // *** End programmer edit section *** (Колонка.НомерКол Set end)
            }
        }
        
        /// <summary>
        /// Колонка.
        /// </summary>
        // *** Start programmer edit section *** (Колонка.ЗаправБак CustomAttributes)

        // *** End programmer edit section *** (Колонка.ЗаправБак CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаправБак"})]
        [NotNull()]
        public virtual IIS.KURSAVAYA.ЗаправБак ЗаправБак
        {
            get
            {
                // *** Start programmer edit section *** (Колонка.ЗаправБак Get start)

                // *** End programmer edit section *** (Колонка.ЗаправБак Get start)
                IIS.KURSAVAYA.ЗаправБак result = this.fЗаправБак;
                // *** Start programmer edit section *** (Колонка.ЗаправБак Get end)

                // *** End programmer edit section *** (Колонка.ЗаправБак Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Колонка.ЗаправБак Set start)

                // *** End programmer edit section *** (Колонка.ЗаправБак Set start)
                this.fЗаправБак = value;
                // *** Start programmer edit section *** (Колонка.ЗаправБак Set end)

                // *** End programmer edit section *** (Колонка.ЗаправБак Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КолонкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КолонкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КолонкаE", typeof(IIS.KURSAVAYA.Колонка));
                }
            }
            
            /// <summary>
            /// "КолонкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КолонкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КолонкаL", typeof(IIS.KURSAVAYA.Колонка));
                }
            }
        }
    }
}
