//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KURSAVAYA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "Наименование as \'Наименование\'",
            "Цена as \'Цена\'",
            "Количество as \'Количество\'"})]
    [View("ТоварL", new string[] {
            "Наименование as \'Наименование\'",
            "Цена as \'Цена\'",
            "Количество as \'Количество\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private float fЦена;
        
        private int fКоличество;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Количество CustomAttributes)

        // *** End programmer edit section *** (Товар.Количество CustomAttributes)
        [NotNull()]
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Количество Get start)

                // *** End programmer edit section *** (Товар.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Товар.Количество Get end)

                // *** End programmer edit section *** (Товар.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Количество Set start)

                // *** End programmer edit section *** (Товар.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Товар.Количество Set end)

                // *** End programmer edit section *** (Товар.Количество Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Наименование CustomAttributes)

        // *** End programmer edit section *** (Товар.Наименование CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Наименование Get start)

                // *** End programmer edit section *** (Товар.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Товар.Наименование Get end)

                // *** End programmer edit section *** (Товар.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Наименование Set start)

                // *** End programmer edit section *** (Товар.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Товар.Наименование Set end)

                // *** End programmer edit section *** (Товар.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Цена CustomAttributes)

        // *** End programmer edit section *** (Товар.Цена CustomAttributes)
        [NotNull()]
        public virtual float Цена
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Цена Get start)

                // *** End programmer edit section *** (Товар.Цена Get start)
                float result = this.fЦена;
                // *** Start programmer edit section *** (Товар.Цена Get end)

                // *** End programmer edit section *** (Товар.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Цена Set start)

                // *** End programmer edit section *** (Товар.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Товар.Цена Set end)

                // *** End programmer edit section *** (Товар.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.KURSAVAYA.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.KURSAVAYA.Товар));
                }
            }
        }
    }
}
