//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KURSAVAYA
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Чек.
    /// </summary>
    // *** Start programmer edit section *** (Чек CustomAttributes)

    // *** End programmer edit section *** (Чек CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЧекE", new string[] {
            "Сумма as \'Сумма\'",
            "Заказ as \'Заказ\'",
            "Заказ.НомерЗаказа as \'Номер заказа\'"}, Hidden=new string[] {
            "Заказ.НомерЗаказа"})]
    [MasterViewDefineAttribute("ЧекE", "Заказ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЗаказа")]
    [View("ЧекL", new string[] {
            "Сумма as \'Сумма\'",
            "Заказ.НомерЗаказа as \'Номер заказа\'",
            "Заказ.Клиент"})]
    public class Чек : ICSSoft.STORMNET.DataObject
    {
        
        private float fСумма;
        
        private IIS.KURSAVAYA.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (Чек CustomMembers)

        // *** End programmer edit section *** (Чек CustomMembers)

        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Сумма CustomAttributes)

        // *** End programmer edit section *** (Чек.Сумма CustomAttributes)
        public virtual float Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Сумма Get start)

                // *** End programmer edit section *** (Чек.Сумма Get start)
                float result = this.fСумма;
                // *** Start programmer edit section *** (Чек.Сумма Get end)

                // *** End programmer edit section *** (Чек.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Сумма Set start)

                // *** End programmer edit section *** (Чек.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Чек.Сумма Set end)

                // *** End programmer edit section *** (Чек.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Чек.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Заказ CustomAttributes)

        // *** End programmer edit section *** (Чек.Заказ CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказ"})]
        [NotNull()]
        public virtual IIS.KURSAVAYA.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Заказ Get start)

                // *** End programmer edit section *** (Чек.Заказ Get start)
                IIS.KURSAVAYA.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (Чек.Заказ Get end)

                // *** End programmer edit section *** (Чек.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Заказ Set start)

                // *** End programmer edit section *** (Чек.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (Чек.Заказ Set end)

                // *** End programmer edit section *** (Чек.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЧекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧекE", typeof(IIS.KURSAVAYA.Чек));
                }
            }
            
            /// <summary>
            /// "ЧекL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧекL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧекL", typeof(IIS.KURSAVAYA.Чек));
                }
            }
        }
    }
}
